name: CI
on:
  push:
    branches: [ mbcs-mwl-001 ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Clean and Checkout
        shell: cmd
        run: |
          if exist C:\mbcs_repo rmdir /s /q C:\mbcs_repo
          git clone http://mbcsadmin:fff92a248a1d50edcaeed7e8fb78f0e030bc847a@localhost:3001/mbcsadmin/MBCS.git C:\mbcs_repo --depth 1
      - name: Test
        shell: cmd
        working-directory: C:\mbcs_repo\bank-core
        run: mvn test -s C:\mbcs_repo\bank-maven\settings.xml
