#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Wed Jun 03 16:12:23 CST 2026
maven-metadata-aliyunmaven.xml/@default-aliyunmaven-https\://maven.aliyun.com/repository/public/.lastUpdated=1780474343996
maven-metadata-aliyunmaven.xml.error=Could not transfer metadata com.bank\:bank-liability\:1.0.0-SNAPSHOT/maven-metadata.xml from/to aliyunmaven (https\://maven.aliyun.com/repository/public)\: transfer failed for https\://maven.aliyun.com/repository/public/com/bank/bank-liability/1.0.0-SNAPSHOT/maven-metadata.xml
