server:
  port: 8080

spring:
  application:
    name: bank-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bank_core?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    db-config:
      id-type: auto
  type-handlers-package: com.bank.common.infrastructure.persistence.handler,com.bank.liability.infrastructure.persistence.handler,com.bank.customer.infrastructure.persistence.handler,com.bank.teller.infrastructure.persistence.handler

logging:
  config: classpath:logback-spring.xml